# https://github.com/cenk1cenk2/drone-semantic-release

kind: pipeline
trigger:
  event:
    - push
  branch:
    - master

steps:
  - name: semantic-release
    image: cenk1cenk2/drone-semantic-release
    settings:
      semantic_release: true
      git_method: gl
      git_user_name:
        from_secret: user_name_jass
      git_user_email:
        from_secret: user_email_jass
      gitlab_token:
        from_secret: jass_token
      update_readme_toc: true

