# semantic-release >> https://github.com/cenk1cenk2/drone-semantic-release
#   gitlab-release >> http://plugins.drone.io/appleboy/drone-gitlab-ci/
#

kind: pipeline
name: semver
trigger:
  event:
    - push
  branch:
    - master

steps:
  - name: semantic-release
    image: cenk1cenk2/drone-semantic-release
    settings:
      mode: "release"
      update_readme_toc: false
      use_local_rc: true
      semantic_release: true
      git_method: gl
      git_user_name:
        from_secret: user_name_jass
      git_user_email:
        from_secret: user_email_jass
      gitlab_token:
        from_secret: jass_token
#  - name: gitlab-release
#    image: appleboy/drone-gitlab-ci
#    settings:
#      host: https://gitlab.jassuncao.work
#      token:
#        from_secret: jass_token
#      id: 19
#      ref: master
#      debug: true

#---
#kind: pipeline
#name: testing release
#
#steps:
#- name: release
#  image: solutisdigital/drone-gitlab-releases
#  settings:
#    assets: asset.zip
#    token:
#      from_secret: jass_token
