---

kind: pipeline
type: docker
name: semantic-release

steps:
  - name: build
    image: node:12.14.0-buster
    settings:
      add_modules: "@semantic-release/gitlab-config"
    environment:
      GIT_AUTHOR_NAME:
        from_secret: user_name_jass
      GIT_AUTHOR_EMAIL:
        from_secret: user_email_jass
      GIT_COMMITTER_NAME:
        from_secret: user_name_jass
      GIT_COMMITTER_EMAIL:
        from_secret: user_email_jass
      GITLAB_TOKEN:
        from_secret: jass_token
      NPM_TOKEN:
        from_secret: npm_token

    commands:
      - npm i fsevents@latest -f --save-optional
#      - npm i --silent
      - npm i
      - npx semantic-release
    when:
      branch:
        - master

  - name: release
    image: registry.gitlab.com/gitlab-org/release-cli:v0.1.0
    script:
      - gitlab-releaser create --name="My Release" --description="My Release description"
