---

# NOT READY! DO NOT USE!

version: "3.8"
services:
  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - <path to data>:/config
    ports:
      - 8181:8181
    restart: unless-stopped
